version: '3.6'

services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ganuroth12
    volumes:
      - mongodata:/data/db
  indexer:
    image: "node:carbon"
    user: "node"
    depends_on:
      - db
    working_dir: /home/pieperson
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/pieperson
    links:
      - "db:database"
    command: "yarn indexer"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - "db:database"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ganuroth12
  # web:
  #   image: "node:carbon"
  #   user: "node"
  #   depends_on:
  #     - db
  #   working_dir: /home/pieperson
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/home/pieperson
  #   links:
  #     - "db:database"
  #   command: "yarn start"
  # watch:
  #   image: "node:carbon"
  #   user: "node"
  #   depends_on:
  #     - web
  #   working_dir: /home/pieperson
  #   restart: always
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/home/pieperson
  #   ports:
  #     - "3001:3001"
  #   links: 
  #     - "web:proxy"
  #   command: "yarn watch"
volumes:
  mongodata: