const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const itemSchema = new Schema({
  abyssJewel: Boolean,
  additionalProperties: [Schema.Types.Mixed],
  artFilename: String,
  category: [Schema.Types.Mixed],
  corrupted: Boolean,
  cosmeticMods: [String],
  craftedMods: [String],
  descrText: String,
  duplicated: Boolean,
  elder: Boolean,
  enchantMods: [String],
  explicitMods: [String],
  flavourText: [String],
  frameType: String,
  h: Number,
  icon:	String,
  id: String,
  identified:	Boolean,
  ilvl: Number,
  implicitMods: [String],
  inventoryId: String,
  isRelic: Boolean,
  league: String,
  lockedToCharacter: Boolean,
  maxStackSize: Number,
  name: String,
  nextLevelRequirements: [Schema.Types.Mixed],
  note:	String,
  properties: [Schema.Types.Mixed],
  prophecyDiffText:	String,
  prophecyText: String,
  requirements: [Schema.Types.Mixed],
  secDescrText: String,
  shaper: Boolean,
  socketedItems: [Schema.Types.Mixed],
  sockets: [Schema.Types.Mixed],
  stackSize: Number,
  support: Boolean,
  talismanTier: Number,
  typeLine: String,
  utilityMods: [String],
  verified: Boolean,
  w: Number,
  x: Number,
  y: Number
});

module.exports = mongoose.model('Item', itemSchema);
